Update to Master for fixes.
automatic-ripping-machine/automatic-ripping-machine pull request #363
Opened 2020-10-26 04:00 UTC by flammableliquids

Read comments for full details.
Added functionality to curtail number of concurrent handbrake jobs.
Added a logging fix to not pump to the same log file.
Updated readme instructions to be a little more functional, and also to enable nvenc support, plus refer to the correct repo.

2020-10-26 13:52 UTC, colonelpopcorn commented
Fix conflicts in readme?

2020-10-26 21:53 UTC, flammableliquids commented
> 
> 
> Fix conflicts in readme?

Fixed this now.

2020-10-27 09:52 UTC, colonelpopcorn requested changes
Refactoring to a function in `handbrake.py` is just a suggestion, but it would be nice if you could change the `ilogfull` and `iilogfull` names to something more meaningful in `logger.py`

2020-10-27 09:52 UTC, colonelpopcorn commented on arm/ripper/handbrake.py
> +
Could this be extracted into a method/function? It just seems like a code smell to me that there's a duplicate here.

2020-10-27 09:52 UTC, colonelpopcorn commented on arm/ripper/handbrake.py
> +    job.status = "transcoding"
See my comment above.

2020-10-27 09:52 UTC, colonelpopcorn commented on arm/ripper/logger.py
> +        iilogfull = cfg['LOGPATH'] + "/" + logfile
More verbosity in variable names would be good, I don't understand what iilogfull means.

2020-10-27 09:52 UTC, colonelpopcorn commented on arm/ripper/logger.py
> +        ilogfull = cfg['LOGPATH'] + logfile
More verbosity in variable names would be good, I don't understand what ilogfull means.

2020-10-27 09:52 UTC, colonelpopcorn commented on arm/ripper/utils.py
> +        logging.info("Error: The 'new' directory already exists, ARM will probably copy the newly ripped folder into the old-new folder.")
Could be good to open an issue for this, just to keep track of it.

2020-10-30 02:56 UTC, closed without merging

2020-10-30 02:57 UTC, flammableliquids commented
Closing, will modify and re-submit

2020-11-12 11:10 UTC, flammableliquids commented
@colonelpopcorn please review #366