Move makemkv progress into own logs
automatic-ripping-machine/automatic-ripping-machine pull request #767
Opened 2023-02-26 01:33 UTC by 1337-server

# Description
Moves the makeMKV progress logs into its own log as with UHD and large bluray logs become large and annoying to read

Fixes # (issue title here)

## Type of change
Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

- [ ] Docker
- [ ] Other (Please state here)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have tested that my fix is effective or that my feature works

# Changelog:

Include the details of changes made here
- Change 1
- Change 2

# Logs
Attach logs from successful test runs here

2023-03-02 03:44 UTC, shitwolfymakes commented
Rather than redirecting these to a new log file, can we create a MakeMKV/Hanbrake "level" of logging, below even debug?

If that's not possible, we could always make including the logs in the regular logfile a setting in arm.yaml

2023-03-02 03:45 UTC, 1337-server commented
> Rather than redirecting these to a new log file, can we create a MakeMKV/Hanbrake "level" of logging, below even debug?
> 
> If that's not possible, we could always make including the logs in the regular logfile a setting in arm.yaml

The problem with this is that these progress logs are needed for keeping track of progress/progress bar on the homepage. Without them it just shows the current status and not the ETA or job progress.

2023-03-02 03:47 UTC, shitwolfymakes commented
> The problem with this is that these progress logs are needed for keeping track of progress/progress bar on the homepage. Without them it just shows the current status and not the ETA or job progress.

Ah, shit. Is that how you got that working? I would image doing it that way was your last resort?

2023-03-02 23:20 UTC, 1337-server commented
It's the only way I can think of doing it. I'm not sure if we have any other option, as there is no update output other than the progress logs.
The alternative at the time was to tail the current log and wait for updates. But I hated that and wanted updates on the homepage.

2023-03-10 07:19 UTC, 1337-server commented
This is ready for review.

2023-03-12 00:02 UTC, shitwolfymakes requested changes

2023-03-12 00:02 UTC, shitwolfymakes commented on arm/ripper/makemkv.py
> +            cmd = f'makemkvcon mkv {job.config.MKV_ARGS} -r ' \
Please add a comment explaining what this command does

2023-03-12 00:02 UTC, shitwolfymakes commented on arm/ui/json_api.py
>      Process the logfile and find current status\n
Update docstring, and clarify how this function works

2023-03-12 00:02 UTC, shitwolfymakes commented on arm/ripper/logger.py
> +    for log_dir in logs_folders:
Explain what this loop does

2023-03-17 19:47 UTC, 1337-server commented on arm/ripper/makemkv.py
> +        cmd = f'makemkvcon backup --decrypt {job.config.MKV_ARGS} --minlength={job.config.MINLENGTH}' \
The comment is right above it ?

2023-03-17 19:47 UTC, 1337-server commented on arm/ripper/makemkv.py
> +            cmd = f'makemkvcon mkv {job.config.MKV_ARGS} -r ' \
Line 68

2023-03-19 16:50 UTC, 1337-server commented
Ready for re-review.

2023-04-01 19:02 UTC, merged