Minor enhancment ARM devtools add docker tool
automatic-ripping-machine/automatic-ripping-machine pull request #788
Opened 2023-03-13 11:37 UTC by microtechno9000

# Description
ARM Developer tools, added command that allows for docker management

`./armdevtools.py -dr /home/arm/armdocker.bash `
```
./armdevtools.py -h
usage: armdevtools.py [-h] [-b B] [-d] [-dr DR] [-db_rem] [-db_data] [-qa] [-pr] [-v]

Automatic Ripping Machine Development Tool Scripts

options:
  -h, --help  show this help message and exit
...
  -dr DR      Docker rebuild post ARM code update. Requires docker run script path to run.
...
```

Fixes # n/a

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?
Ubuntu 20.04

- [x] Docker
- [x] Ubuntu 20.04

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have tested that my fix is effective or that my feature works

# Changelog:
as above, added docker command to armdevtools

# Logs
Attach logs from successful test runs here
[armdevtool_log.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10956849/armdevtool_log.txt)

2023-03-14 04:35 UTC, shitwolfymakes commented
Please add documentation (examples) for each use case, forgot to request this last time.

2023-03-14 05:12 UTC, microtechno9000 commented
There is a readme in the armdevtools folder, do you want this added to the Wiki?

2023-03-14 05:32 UTC, shitwolfymakes commented
The README is a good overview of the capability, but is insufficient. For full tutorials the wiki would be a better place.

2023-03-14 12:40 UTC, microtechno9000 commented
Details added to the wiki
https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/ARM-Development-Tools

2023-03-15 01:27 UTC, shitwolfymakes commented
Great work on the documentation!

2023-03-15 01:31 UTC, shitwolfymakes requested changes

2023-03-15 01:31 UTC, shitwolfymakes commented on devtools/armdevtools.py
> +# parser.add_argument("-d",
Remove this commented code

2023-03-15 01:31 UTC, shitwolfymakes commented on devtools/armdevtools.py
> +# parser.add_argument("-db_data",
Review this commented code

2023-03-15 01:31 UTC, shitwolfymakes commented on devtools/armdevtools.py
> +# -d Delete/Clear arm home drive data [currently unsupported]
Remove this commented code

2023-03-15 01:31 UTC, shitwolfymakes commented on devtools/armdevtools.py
> +# -db_data Database data insert [currently unsupported]
Remove this commented code

2023-03-15 01:31 UTC, shitwolfymakes commented on devtools/armui.py
>  #  INPUT: none
Remove redundant comments

2023-03-15 03:41 UTC, microtechno9000 commented on devtools/armdevtools.py
> +# parser.add_argument("-db_data",
Removed comments

2023-03-15 03:41 UTC, microtechno9000 commented on devtools/armdevtools.py
> +# -db_data Database data insert [currently unsupported]
Removed comments

2023-03-15 03:42 UTC, microtechno9000 commented on devtools/armdevtools.py
> +# parser.add_argument("-d",
Removed comments

2023-03-15 03:42 UTC, microtechno9000 commented on devtools/armui.py
>  #  INPUT: none
Removed comments

2023-03-15 04:05 UTC, shitwolfymakes approved these changes
Good to go. Keep up the great work!

2023-03-15 04:05 UTC, merged